# Generated by Django 3.0.8 on 2020-07-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=128)),
                ('description', models.CharField(default=' ', max_length=256)),
                ('cover', models.ImageField(upload_to='covers/', verbose_name='Обложка')),
                ('date', models.DateField()),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=128)),
                ('age', models.IntegerField(default='7')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=128)),
                ('age', models.IntegerField(default='7')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=' ', max_length=128)),
                ('second_name', models.CharField(default=' ', max_length=128)),
                ('avatar', models.ImageField(upload_to='authors/', verbose_name='Изображение')),
                ('books', models.ManyToManyField(to='core.Book')),
            ],
        ),
    ]
